server:
  port: 8080

spring:
  application:
    name: customer
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      formate_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: 4321
    driverClassName: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true